version: "2.1"
orbs:
    node: circleci/node@5.0.2

jobs:
    all:
        docker:
            - image: "cimg/base:stable"
            - image: "cimg/postgres:14.0"

        steps:
            - checkout
            - node/install:
                install-yarn: true
                node-version: "16.13"
            - run:
                name: install dependancy
                command: yarn install
            - run:
                name: build project
                command: yarn build
            - run:
                name: test api
                command: yarn test:api

workflow:
    install-build-test-deploy:
        jobs:
            - all