version: "2.1"
orbs:
    node: circleci/node@5.0.2
    aws-cli: circleci/aws-cli@3.1.1
    eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
    one:
        docker:
             - image: "cimg/base:stable"

        steps:
            - checkout
            - node/install:
                install-yarn: true
                node-version: "16.13"
            - run:
                name: install dependancy
                command: yarn install
            - aws-cli/setup
            - eb/setup
            - run:
                name: build project
                command: yarn build
            - run:
                name: test frontend
                command: yarn test:front
            - run:
                name: deploy project
                command: yarn deploy
            

workflows:
  all_in_one: 
    jobs: 
      - one
